# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dff367e2d8c218f56c8cadd6c73f0d7f0ab94ca5e7bc806f643f5c274d837d3a499608a1409c5881aef4dc055a40c5b682e8ddf918769095764b0ea9900f968

test:
  secret_key_base: 423ce9c83b6b372c97057445e3bd780d1e2497ad87cd7cc7f89573715006c647ec926fb486dc746d295fe58ff177e7928413bd272f58ca09b02eb0b9448dfa16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
